version: "3.0"

services:

  vpn:
    container_name: vpn
    restart: unless-stopped
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # openvpn port
      - "1194:1194/udp"
      # Flood
      - "3000:3000"
      # rtorrent
      - "16891:16891"
      - "6881:6881"
      - "50000:50000"
    volumes:
      - ${BASE_PATH}/vpn:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_CUSTOM_CONFIG=/gluetun/raspberry.ovpn
      - FIREWALL=on
      - FIREWALL_VPN_INPUT_PORTS=3000,50000,6881
      - FIREWALL_DEBUG=on
      - TZ=${TIMEZONE}

  flood:
    container_name: flood
    restart: unless-stopped
    build: docker/flood
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ${DOWNLOAD_FOLDER_PATH}:/srv/rtorrent/download

      - ${BASE_PATH}/docker/flood/config.js:/srv/flood/config.js
      - ${BASE_PATH}/data/flood-db:/data/flood-db

  rtorrent:
    container_name: rtorrent
    restart: unless-stopped
    build: docker/rtorrent
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - USER_UID=${USER_ID}
      - USER_GID=${GROUP_ID}
    volumes:
      - ${BASE_PATH}/docker/rtorrent/config.d:/srv/rtorrent/config.d
      - ${BASE_PATH}/downloads:/srv/rtorrent/download
      - ${BASE_PATH}/logs:/srv/rtorrent/log
      - ${BASE_PATH}/data/session:/srv/rtorrent/.session

  samba:
    image: dperson/samba:armhf
    container_name: samba
    environment:
      TZ: ${TIMEZONE}
      USERID: ${USER_ID}
      GROUPID: ${GROUP_ID}
      # advertise shares, default: true, or false (open ports 137, 138)
      NMBD: "true"
      WORKGROUP: "WORKGROUP"
      # add a single share. If you need more, use command instead of environment
      # required arg: "<name>;</path>"
      # <share_name>;
      # <path_to_share>;
      # [browsable] default:'yes' or 'no';
      # [read_only] default:'yes' or 'no';
      # [guest]: default: 'yes' or 'no';
      # [users]: default: 'all' or list of allowed users;
      # [admins] default: 'none' or list of admin users;
      # [writelist] default: 'none' or list of users that can write to read-only share;
      # [comment] default: 'none' or description of share
      SHARE: "raspberry;/mnt;yes;no;yes;all;'none';'none';'Raspberry'"
    networks:
      - default
    ports:
      - "137:137/udp" # required to advertise shares (NMBD)
      - "138:138/udp" # required to advertise shares (NMBD)
      - "139:139/tcp" # default smb port
      - "445:445/tcp" # default smb port
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
     # - /home/pi/seedbox/docker/samba/smb.conf:/etc/samba/smb.conf
      - ${DOWNLOAD_FOLDER_PATH}:/mnt:z
    # command: '-s "usbhub;/mnt;yes;no;yes;" -p' # USB Hub should have access to anyone for anything
    #command: '-s "usbhub;/mnt" -s "Bobs Volume;/mnt2;yes;no;no;bob" -u "bob;bobspasswd"'

  minidlna:
    container_name: minidnla
    restart: unless-stopped
    image: cytomich/rpi-docker-minidlna
    volumes:
      - ${DOWNLOAD_FOLDER_PATH}:/media:z
    environment:
      - MINIDLNA_MEDIA_DIR=/media
      - MINIDLNA_PORT=8200
      - MINIDLNA_FRIENDLY_NAME=Raspberry
    network_mode: "host"

networks:
  seedbox-network:
    driver: bridge