
services:

  vpn:
    container_name: vpn
    restart: unless-stopped
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # openvpn port
      - "1194:1194/udp"
      # Flood
      - ${FLOOD_PORT}:${FLOOD_PORT}
      # rtorrent
      - "16891:16891"
      - ${RTORRENT_PEER_PORT}:${RTORRENT_PEER_PORT}
      - ${RTORRENT_DHT_PORT}:${RTORRENT_DHT_PORT}
      # qBittorrent
      - ${QBITTOTTENT_PEER_PORT}:${QBITTOTTENT_PEER_PORT}
    volumes:
      - ${BASE_PATH}/vpn:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_CUSTOM_CONFIG=/gluetun/raspberry.ovpn
      - FIREWALL=on
      - FIREWALL_VPN_INPUT_PORTS=3000,${RTORRENT_PEER_PORT},${RTORRENT_DHT_PORT},${QBITTOTTENT_PEER_PORT}
      - FIREWALL_DEBUG=on
      - TZ=${TIMEZONE}