version: "3.0"

services:

  ########################################################################
  # Flood
  ########################################################################
  flood-base: &flood-base
    container_name: flood
    restart: unless-stopped
    image: ghcr.io/chris3481/flood:latest
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ${BASE_PATH}/docker/flood/config.js:/srv/flood/config.js
      - ${BASE_PATH}/data/flood-db:/data/flood-db

  flood-vpn:
    <<: *flood-base
    network_mode: service:vpn

  flood-standalone:
    <<: *flood-base
    ports:
      - "3000:3000"
    networks:
      - seedbox-network

  ########################################################################
  # rTorrent
  ########################################################################
  rtorrent-base: &rtorrent-base
    container_name: rtorrent
    restart: unless-stopped
    image: ghcr.io/chris3481/rtorrent:latest
    environment:
      - USER_UID=${USER_ID}
      - USER_GID=${GROUP_ID}
    volumes:
      - ${BASE_PATH}/docker/rtorrent/config.d:/srv/rtorrent/config.d
      - ${DOWNLOAD_FOLDER_PATH}:/srv/rtorrent/download
      - ${BASE_PATH}/logs:/srv/rtorrent/log
      - ${BASE_PATH}/data/rtorrent/sessions:/srv/rtorrent/.session

  rtorrent-vpn:
    <<: *rtorrent-base
    network_mode: service:vpn

  rtorrent-standalone:
    <<: *rtorrent-base
    ports:
      - "16891:16891"
      - "6881:6881"
      - "50000:50000"
    networks:
      - seedbox-network

  ########################################################################
  # qBittorrent
  ########################################################################
  qbittorrent-base: &qbittorrent-base
    container_name: qbittorrent
    restart: unless-stopped
    image: gists/qbittorrent:4.4.3
    environment:
      - PEER_PORT=6881
      - WEB_PORT=8080
      - UID=${USER_ID}
      - GID=${GROUP_ID}
    volumes:
      - ${BASE_PATH}/data/qBittorrent:/data/.config/qBittorrent
      - ${DOWNLOAD_FOLDER_PATH}:/data/downloads

  qbittorrent-vpn:
    <<: *qbittorrent-base
    network_mode: service:vpn

  qbittorrent-standalone:
    <<: *qbittorrent-base
    ports:
      - "8080:8080"
      - "6882:6881"
      - "6881:6881/udp"
    networks:
      - seedbox-network

networks:
  seedbox-network:
    driver: bridge